#!/bin/python3
def func(x):
    x = str(eval(x))
    l = len(x)
    for i in range(l, l%3, -3):
        if x[:i-3]:
            x = f'{x[:i-3]}_{x[i-3:i]}{x[i:]}'
        else:
            x = f'{x[i-3:i]}{x[i:]}'
    return x

if __name__ == "__main__":
	print('\n'.join(map(func, open(0).read().splitlines())))
