#!/usr/bin/env bash

mountpoint="$HOME/mnt/usb"

if [ $# -eq 1 ]; then
	mountpoint=$1
fi
echo $mountpoint

mount=$(lsblk --list --output PATH,MOUNTPOINTS | awk 'BEGIN { FS = " " } { if(!$2){print $1} }' | fzf)
if [ $mount ]; then
	sudo mount -o gid=1000,uid=1000 $mount $mountpoint
fi
