#!/usr/bin/env bash

gen=$(echo $(ls -c /nix/var/nix/profiles | grep system- | head -n1 | get-numbers)+1 | calc)
cd $HOME/Code/nixos/
nvim configuration.nix
if [ "$(git diff)" != "" ]
then
	sudo nixos-rebuild switch --impure --show-trace --flake . && git commit -am "generation $gen"
fi
