#!/usr/bin/env sh
# Script to start a new project using a template form the users Template directory
# requires fzf
if [ $# -ne 1 ]; then
	>&2 echo "use one argument 'Project Name'"
fi

templatedir=$HOME/Templates/
template=$(ls $templatedir | fzf)

cp -r $templatedir/$template ./$1

nvim $1
