#!/usr/bin/env sh

point=30
width=500
caption=$1
in=$2
out=$3

magick \
  -size 500x -background white -gravity center -pointsize $point caption:"$caption" \
  -set option:HH %h \
  +delete \
  $in  \
  -layers coalesce \
  -resize $width\x -background None -gravity North -splice '0x%[HH]+0+0' \
  NULL: \
  -size $width\x -background white -gravity center -pointsize $point caption:"$caption" \
  -gravity North -compose Over -layers composite \
  -layers optimize \
  $out
