#!/bin/sh

weatherreport="${XDG_CACHE_HOME:-$HOME/.cache}/weatherreport"
last_mod=$(date +'%s' -r $weatherreport)
now=$(date +'%s')

if [ $(($now - $last_mod)) -ge 600 ] || [ ! -s $weatherreport ]; then
    curl "https://api.openweathermap.org/data/2.5/weather?lat=-22.5615068&lon=-47.401766&units=metric&appid=c6ab7fea93b9e1d0f062c0b29b49e143" > $weatherreport
fi

case $BLOCK_BUTTON in
    1) setsid -f alacritty -T weather --hold -e pretty-print-forecast;;
	6) alacritty -e nvim "$0" ;;
esac

temp=$(jq .main.temp < $weatherreport)

echo $temp°C
