#!/usr/bin/env bash

case $BLOCK_BUTTON in
    1) sleep-toggle&;;
    # 3) xscreensaver_sleep &;;
    6) "alacritty" -e "nvim" "$0" &;;
esac

status=$(xset -q | grep "DPMS is")

if [ "$status" = "  DPMS is Enabled" ]; then
	echo "💤"
else
	echo "☕"
fi
