#! /bin/bash
case $BLOCK_BUTTON in
    1) toggle_xscreensaver &;;
    3) xscreensaver_sleep &;;
    6) "alacritty" -e "nvim" "$0" &;;
esac

active=$(systemctl --user is-active xscreensaver)
if [ $active == "active" ]; then
    echo "💤"
else
    echo "☕"
fi
