#! /bin/bash

sed -i -- "s/\/home\/eppi\/.config\/alacritty\/themes\/themes\/gruvbox_light.toml/\/home\/eppi\/.config\/alacritty\/themes\/themes\/gruvbox.toml/" \
    ~/.config/alacritty/alacritty.toml

