#! /bin/bash

sed -i -- "s/\/home\/eppi\/.config\/alacritty\/themes\/themes\/rose-pine-dawn.toml/\/home\/eppi\/.config\/alacritty\/themes\/themes\/rose-pine.toml/" \
    ~/.config/alacritty/alacritty.toml

